-define(LOGIN_ERROR_OK, "OK").
-define(LOGOUT_ERROR_OK, "OK").
-define(LOGOUT_ERROR_API_ERROR, "API_ERROR").

-define(GET_EVENTS_ERROR_OK, "OK").
-define(GET_EVENTS_ERROR_INVALID_EVENT_ID, "INVALID_EVENT_ID").
-define(GET_EVENTS_ERROR_NO_RESULTS, "NO_RESULTS").
-define(GET_EVENTS_ERROR_INVALID_LOCALE_DEFAULTING_TO_ENGLISH, "INVALID_LOCALE_DEFAULTING_TO_ENGLISH").
-define(GET_EVENTS_ERROR_API_ERROR, "API_ERROR").
