-define(LOGIN_ERROR_OK, "OK").
-define(LOGOUT_ERROR_OK, "OK").
-define(LOGOUT_ERROR_API_ERROR, "API_ERROR").

-define(GET_EVENTS_ERROR_OK, "OK").
-define(GET_EVENTS_ERROR_INVALID_EVENT_ID, "INVALID_EVENT_ID").
-define(GET_EVENTS_ERROR_NO_RESULTS, "NO_RESULTS").
-define(GET_EVENTS_ERROR_INVALID_LOCALE_DEFAULTING_TO_ENGLISH, "INVALID_LOCALE_DEFAULTING_TO_ENGLISH").
-define(GET_EVENTS_ERROR_API_ERROR, "API_ERROR").

-define(GET_ALL_MARKETS_ERROR_OK, "OK").
-define(GET_ALL_MARKETS_ERROR_API_ERROR, "API_ERROR").
-define(GET_ALL_MARKETS_ERROR_INVALID_COUNTRY_CODE, "INVALID_COUNTRY_CODE").
-define(GET_ALL_MARKETS_ERROR_INVALID_EVENT_TYPE_ID, "INVALID_EVENT_TYPE_ID").
-define(GET_ALL_MARKETS_ERROR_INVALID_LOCALE, "INVALID_LOCALE").

-define(GET_MARKET_ERROR_OK, "OK").
-define(GET_MARKET_ERROR_API_ERROR, "API_ERROR").
-define(GET_MARKET_ERROR_MARKET_TYPE_NOT_SUPPORTED, "MARKET_TYPE_NOT_SUPPORTED").
-define(GET_MARKET_ERROR_INVALID_MARKET, "INVALID_MARKET").
-define(GET_MARKET_ERROR_INVALID_LOCALE_DAFAULTING_TO_ENGLISH, "INVALID_LOCALE_DAFAULTING_TO_ENGLISH").

-define(GET_BET_ERROR_OK, "OK").
-define(GET_BET_ERROR_API_ERROR, "API_ERROR").
-define(GET_BET_ERROR_BET_ID_INVALID, "BET_ID_INVALID").
-define(GET_BET_ERROR_INVALID_LOCALE_DAFAULTING_TO_ENGLISH, "INVALID_LOCALE_DAFAULTING_TO_ENGLISH").
-define(GET_BET_ERROR_MARKET_TYPE_NOT_SUPPORTED, "MARKET_TYPE_NOT_SUPPORTED").
-define(GET_BET_ERROR_NO_RESULTS, "NO_RESULTS").

-define(GET_MARKET_PRICES_ERROR_OK, "OK").
-define(GET_MARKET_PRICES_ERROR_API_ERROR, "API_ERROR").
-define(GET_MARKET_PRICES_INVALID_CURRENCY, "INVALID_CURRENCY").
-define(GET_MARKET_PRICES_INVALID_MARKET, "INVALID_MARKET").
-define(GET_MARKET_PRICES_MARKET_TYPE_NOT_SUPPORTED, "MARKET_TYPE_NOT_SUPPORTED").



